WOCShAck#3/website/wocshack3/blog_DIY/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin  #  Use it for access to the Django Admin's page
from . import views


urlpatterns = [
    # User
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/<str:uuid>', views.profile, name='profile'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('reset_password/<str:hash>', views.reset_password_hash, name='reset_password_hash'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('admin/', views.admin, name='admin'),  # Custom admin's page
    # path('admin/', admin.site.urls),  #  for access to the Django Admin's page
    path('admin/delete_user/<str:id>', views.admin_delete_user, name='admin_delete_user'),
    path('admin/delete_tutorial/<int:id>', views.admin_delete_tutorial, name='admin_delete_tutorial'),
    path('admin/delete_comment/<int:id>', views.admin_delete_comment, name='admin_delete_comment'),
    # Tutorials
    path('add_tutorial/', views.add_tutorial, name='add_tutorial'),
    path('delete_tutorial/<int:id>', views.delete_comment, name='delete_comment'),
    path('edit_tutorial/<int:id>/', views.edit_tutorial, name='edit_tutorial'),
    path('delete_tutorial/<int:id>/', views.delete_tutorial, name='delete_tutorial'),
    path('my_tutorials/', views.my_tutorials, name='my_tutorials'),
    path('export_tutorial/<int:id>/', views.export_tutorial_to_xml, name='export_tutorial'),
    path('import_tutorial/', views.import_tutorial_from_xml, name='import_tutorial'),
    path('tutorial/<str:id>', views.tutorial, name='tutorial'),
    path('search_tutorial/', views.search_tutorial, name='search_tutorial'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

WOCShAck#3/website/wocshack3/wocshack3/urls.py
from django.urls import path, include


urlpatterns = [
    path('', include('blog_DIY.urls')),
]

WOCShAck#3/website/wocshack3/blog_DIY/forms.py
from django import forms
from .models import UserProfile, Tutorial, Comment
from django.core.validators import FileExtensionValidator


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}))
    password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}))
    authorize = forms.BooleanField(required=False, label='Authorize Actions Logging')



class RegisterForm(forms.Form):
    username = forms.CharField(max_length=63, widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
    password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}))
    confirm_password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'form-control'}))
    authorize = forms.BooleanField(required=False, label='Authorize Actions Logging')


class UserProfileForm(forms.ModelForm):
    new_email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}))
    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'bio']
        widgets = {
            'profile_picture': forms.FileInput(attrs={'accept':'image/*','class': 'form-control'}),
            'bio': forms.Textarea(attrs={'placeholder': 'Bio', 'class': 'form-control'})
        }
        validators = [FileExtensionValidator(['jpg', 'png', 'jpeg', 'gif'])]


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'placeholder': 'Old Password', 'class': 'form-control'}), label='Old Password')
    new_password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'placeholder': 'New Password', 'class': 'form-control'}), label='New Password')
    confirm_new_password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm New Password', 'class': 'form-control'}), label='Confirm New Password')


class ResetPasswordForm(forms.Form):
    username = forms.CharField(max_length=63, label='Username', widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}))

class ResetOldPasswordForm(forms.Form):
    new_password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'placeholder': 'New Password', 'class': 'form-control'}), label='New Password')
    confirm_new_password = forms.CharField(max_length=63, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm New Password', 'class': 'form-control'}), label='Confirm New Password')


class TutorialForm(forms.ModelForm):
    class Meta:
        model = Tutorial
        fields = ['title']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title', 'class': 'form-control','required':'True'}),
        }


class AddContentForm(forms.Form):
    bodyline = forms.CharField(
        max_length=8000,
        widget=forms.Textarea(attrs={'placeholder': 'Text Content', 'class': 'form-control', 'rows': 5, 'cols': 40,'required':'True'}),
        label='Step description',
    )
    picture = forms.ImageField(
        widget=(forms.FileInput(attrs={'accept':'image/*','class': 'form-control','required':'True'})),
        label='Step picture',
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['bodyline']
        widgets = {
            'bodyline': forms.Textarea(attrs={'placeholder': 'Comment', 'class': 'form-control', 'rows': 2, 'cols': 40}),
        }

WOCShAck#3/website/wocshack3/blog_DIY/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.forms import formset_factory
from django.template import engines
from django.db import connection
from django.conf import settings
from django.db import IntegrityError
from rest_framework_simplejwt.tokens import RefreshToken
from lxml import etree
from . import forms, models
from .authentication import is_valid_token, is_authenticated, redirect_non_admin_user, retrieve_token, \
    redirect_invalid_user, retrieve_user_from_token, is_valid_email, is_valid_password, verif_admin, custom_redirect
import hashlib, jwt, pickle, base64, os
from .logs_manager import log_user_activity, get_logs, Logs
from .models import UserProfile

@log_user_activity("home")
def home(request):
    """
    Render the home page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered home page.
    """
    return render(
        request=request,
        template_name="blog_DIY/home.html",
        context={
            "is_authenticated": is_authenticated(request),
            "is_admin": verif_admin(request)
        }
    )



@log_user_activity("login")
def login_user(request):
    """
    Handle user login.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The login page response.
    """
    # Initialize form, message, and flags
    login_form = forms.LoginForm()
    message = ''
    successful_auth = False
    response = HttpResponse()
    logs = get_logs(request)

    # Check if user is already logged in
    if 'jwt_token' in request.COOKIES:
        token = request.COOKIES['jwt_token']
        if is_valid_token(token):
            # Get user information from the token
            decoded_token = jwt_decode(token, settings.SECRET_KEY, algorithms=['HS256'])
            user = User.objects.get(id=decoded_token['user_id'])
            message = f'You are already connected as {user.username}'
            # Redirect to home page
            return custom_redirect(request, response, '/', message)

    # Process login form submission
    if request.method == 'POST':
        login_form = forms.LoginForm(request.POST)
        if login_form.is_valid():
            # Check if user checked the authorization box
            if login_form.cleaned_data['authorize']:
                logs.log = True
            # Authenticate user
            user = authenticate(
                username=login_form.cleaned_data['username'],
                password=login_form.cleaned_data['password'],
            )
            if user is not None:
                # Generate a new JWT token for the user
                refresh = RefreshToken.for_user(user)
                access_token = str(refresh.access_token)
                # Set JWT token in cookies
                response.set_cookie(key='jwt_token', value=access_token, httponly=True)
                message = f'Hello, {user.username}! You are connected.'
                successful_auth = True
                logs.username = user.username
            else:
                message = 'Invalid credentials.'

    # Encode and set logs cookie
    logs = base64.b64encode(pickle.dumps(logs))
    logs = logs.decode('utf-8')
    response.set_cookie(key='logs', value=logs, httponly=True)

    # Render login template with form, message, and authentication status
    template_content = render(request, 'blog_DIY/login.html', {'login_form': login_form, 'message': message, 'is_authenticated': is_authenticated(request)})
    response.content = template_content.content

    # If authentication was successful, redirect to home page
    if successful_auth:
        response.status_code = 302
        response['Location'] = '/'
    return response




@log_user_activity("logout")
def logout_user(request):
    """
    Handle user logout.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The logout redirect response.
    """
    response = HttpResponse()
    # Delete JWT token, logs, and CSRF token cookies
    if "jwt_token" in request.COOKIES:
        response.delete_cookie("jwt_token")
    if "logs" in request.COOKIES:
        response.delete_cookie("logs")
    if "csrftoken" in request.COOKIES:
        response.delete_cookie("csrftoken")
    # Redirect to login page with logout message
    return custom_redirect(
        request=request,
        response=response,
        location="/login",
        message=f"{get_logs(request).username} logged out"
    )



@log_user_activity("register_user")
def register_user(request):
    """
    Handle user registration.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The registration page response.
    """
    # Initialize form, message, and flags
    register_form = forms.RegisterForm()
    form_valid = True
    successful_register = False
    message = ''
    response = HttpResponse()

    # Get user information from token
    logs = get_logs(request)
    token = retrieve_token(request.COOKIES)
    if not is_valid_token(token):
        redirect_invalid_user(request)
    user = retrieve_user_from_token(token)

    # Process registration form submission
    if request.method == "POST":
        register_form = forms.RegisterForm(request.POST)
        if register_form.is_valid():
            # Validate password
            if register_form.cleaned_data['password'] != register_form.cleaned_data['confirm_password']:
                message = 'Passwords do not match.'
                form_valid = False
            if not is_valid_password(register_form.cleaned_data['password']):
                message = 'The password must contain at least 8 characters, one uppercase letter, and one digit.'
                form_valid = False
            if not is_valid_email(register_form.cleaned_data['email']):
                message = 'Invalid email.'
                form_valid = False
            if form_valid:
                try:
                    # Create new user and user profile
                    user = User.objects.create_user(
                        username=register_form.cleaned_data['username'],
                        password=register_form.cleaned_data['password'],
                        email=register_form.cleaned_data['email'],
                    )
                    user_profile = models.UserProfile.objects.create(
                        user=user,
                        bio='',
                    )
                    message = f'Hello, {user.username}! You are now registered.'
                    # Generate new JWT token for user
                    refresh = RefreshToken.for_user(user)
                    access_token = str(refresh.access_token)
                    response.set_cookie(key='jwt_token', value=access_token, httponly=True, secure=True)
                    logs.username = user.username
                    if register_form.cleaned_data['authorize']:
                        logs.log = True
                    successful_register = True
                except IntegrityError:
                    message = "This username already exists. Please choose another username."
                    form_valid = False
    # Encode and set logs cookie
    logs = base64.b64encode(pickle.dumps(logs))
    logs = logs.decode('utf-8')
    response.set_cookie(key='logs', value=logs, httponly=True)

    # Render registration template with form, message, and authentication status
    template_content = render(request, 'blog_DIY/register.html', {'register_form': register_form, 'message': message, 'is_authenticated': is_authenticated(request)})
    response.content = template_content.content
    # If registration was successful, redirect to home page
    if successful_register:
        response.status_code = 302
        response['Location'] = '/'
    return response



def profile(request, uuid):
    """
    Render user profile page.

    Args:
        request (HttpRequest): The request object.
        uuid (str): The UUID of the user profile.

    Returns:
        HttpResponse: The rendered profile page.
    """
    # Get user profile from UUID
    user = get_object_or_404(models.UserProfile, profile_id=uuid)
    user_profile = user.user.profile
    # Render profile template with user profile, tutorials, and authentication status
    return render(
        request=request,
        template_name="blog_DIY/profile.html",
        context={
            "user_profile": user_profile,
            "tutorials": models.Tutorial.objects.filter(author_user=user_profile, published=True),
            "is_authenticated": is_authenticated(request),
            "is_admin": verif_admin(request)
        }
    )



@log_user_activity("my_profile")
def my_profile(request):
    """
    Render and handle user's own profile page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered profile page.
    """
    # Retrieve user's token
    token = retrieve_token(request.COOKIES)
    if not is_valid_token(token):
        redirect_invalid_user(request)

    # Retrieve user and user profile
    user = retrieve_user_from_token(token)
    user_profile = models.UserProfile.objects.get(user=user)

    message_error = ''
    message_valid = ''

    if request.method == "POST":
        # Process profile form submission
        profile_form = forms.UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if profile_form.is_valid():
            # Check if email format is valid
            if not(is_valid_email(profile_form.cleaned_data["new_email"])):
                profile_form.save()
                message_error = "Invalid email format"
            else:
                profile_form.save()
                message_valid = "Changes saved successfully !"

WOCShAck#3/website/wocshack3/templates/blog_DIY/add_tutorial.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% if not num_formsets %}
    <!-- If no num_formsets variable, show this form -->
    <header class="masthead">
      <section class="page-section" id="contact">
        <div class="container px-4 px-lg-5">
          <div class="row justify-content-center">
            <div class="col-lg-10">
              <h1 class="text-white">Add Tutorial</h1>
              <form method="post" id="num-formset-form">
                {% csrf_token %}
                <label class="text-white" for="num-formsets">Enter the number of steps for your tutorial:</label>
                <input class="form-control" type="number" name="num_formsets" id="num-formsets" min="1" style="margin-bottom: 10px" required />
                <input class="form-control" type="submit" value="Submit" />
              </form>
            </div>
          </div>
        </div>
      </section>
    </header>
  {% else %}
    <!-- If num_formsets variable is present, show this form -->
    <header class="masthead">
      <div class="d-flex flex-column justify-content-center m-5">
        <h2 class="text-white text-center">Add Tutorial</h2>
        <a class="btn btn-primary btn-xl" href="#form_tuto">Add Tutorial</a>
      </div>
    </header>
    <section class="page-section" id="form_tuto">
      <div class="container px-4 px-lg-5">
        <div class="row justify-content-center">
          <div class="col-lg-10">
            <h1 class="text-white">Add Tutorial</h1>
            <form method="post" enctype="multipart/form-data" id="tutorial-form">
              {% csrf_token %}
              <!-- Display the tutorial form -->
              {{ tutorial_form.as_p }}
              <!-- Display the formset management form -->
              {{ formset.management_form }}
              <!-- Container for dynamic formsets -->
              <div id="formset-dynamic-container">
                <!-- Loop through each form in the formset and display it -->
                {% for form in formset.forms %}
                  {{ form.as_p }}
                {% endfor %}
              </div>
              <!-- Buttons for saving draft or publishing -->
              <div class="d-flex justify-content-center">
                <input type="submit" class="btn btn-secondary btn-xl m-1" name="save_draft" value="Save as Draft" />
                <input type="submit" class="btn btn-secondary btn-xl m-1" name="publish" value="Publish" />
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  {% endif %}
{% endblock %}

WOCShAck#3/website/wocshack3/templates/blog_DIY/admin.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- Header section -->
  <header class="masthead">
    <section class="page-section" id="contact">
      <div class="container px-4 px-lg-5">
        <div class="row justify-content-center">
          <div class="col-lg-10">
            <!-- Blog DIY module -->
            <div class="app-blog_DIY module">
              <!-- Table for displaying user profiles, tutorials, and comments -->
              <table>
                <caption>
                  <!-- Link to return to dashboard -->
                  <a href="{% url 'home' %}">Return to dashboard</a>
                </caption>
                <thead>
                  <tr>
                    <!-- Table headers -->
                    <th class="text-white">User Profiles</th>
                    <th class="text-white">Tutorials</th>
                    <th class="text-white">Comments</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <!-- Loop through user profiles and display username with delete link -->
                      {% for user_profile in user_profiles %}
                        <p class="text-white">{{ user_profile.user.username }}</p>
                        <a href="#" class="delete-user" data-url="{% url 'admin_delete_user' user_profile.id %}">Delete User</a><br />
                      {% endfor %}
                    </td>
                    <td>
                      <!-- Loop through tutorials and display title with delete link -->
                      {% for tutorial in tutorials %}
                        <p class="text-white">{{ tutorial.title }}</p>
                        <a href="#" class="delete-tutorial" data-url="{% url 'admin_delete_tutorial' tutorial.id %}">Delete Tutorial</a><br />
                      {% endfor %}
                    </td>
                    <td>
                      <!-- Loop through comments and display bodyline with delete link -->
                      {% for comment in comments %}
                        <p class="text-white">{{ comment.bodyline }}</p>
                        <a href="#" class="delete-comment" data-url="{% url 'admin_delete_comment' comment.id %}">Delete Comment</a><br />
                      {% endfor %}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </header>

  <!-- JavaScript for handling delete confirmation -->
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      document.querySelectorAll('.delete-user, .delete-tutorial, .delete-comment').forEach(function (deleteLink) {
        deleteLink.addEventListener('click', function (e) {
          e.preventDefault()
          // Display confirmation dialog
          var confirmation = confirm('Are you sure you want to delete?')
          // If user confirms, redirect to delete URL
          if (confirmation) {
            window.location.href = deleteLink.getAttribute('data-url')
          }
        })
      })
    })
  </script>
{% endblock %}

WOCShAck#3/website/wocshack3/templates/blog_DIY/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <header class="masthead">
    <section class="page-section" id="contact">
      <div class="container px-4 px-lg-5">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h1 class="text-white">Change Password</h1>
            <form method="post">
              {% csrf_token %}
              <div class="form-floating mb-3 d-flex justify-content-center">
                {{ password_form.old_password }}
                <label for="id_old_password">Old Password</label>
              </div>
              <div class="form-floating mb-3 d-flex justify-content-center">
                {{ password_form.new_password }}
                <label for="id_new_password">New Password</label>
              </div>
              <div class="form-floating mb-3 d-flex justify-content-center">
                {{ password_form.confirm_new_password }}
                <label for="id_confirm_new_password">Confirm New Password</label>
              </div>
              <div class="text-center text-danger mb-3">{{ message }}</div>
              <div class="d-grid">
                <button class="btn btn-primary btn-xl" id="submitButton" type="submit">Change Password</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  </header>
{% endblock %}

WOCShAck#3/website/wocshack3/templates/blog_DIY/delete_user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <header class="masthead">
    <section class="page-section" id="contact">
      <div class="container px-4 px-lg-5">
        <div class="row justify-content-center">
          <div class="col-lg-10">
            <h1 class="text-white">Remove Your Account</h1>
            <p class="text-white">Are you sure you want to remove your account?</p>
            <form method="post">
              {% csrf_token %}
              <div class="d-grid">
                <button class="btn btn-primary btn-xl" id="submitButton" type="submit">Confirm Removal</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  </header>
{% endblock %}

WOCShAck#3/website/wocshack3/templates/blog_DIY/edit_tutorial.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- Header section -->
  <header class="masthead">
    <div class="d-flex flex-column justify-content-center m-5">
      <h2 class="text-white text-center">Edit Tutorial</h2>
      <a class="btn btn-primary btn-xl" href="#form_tuto">Edit Your Tutorial</a>
    </div>
  </header>
  <!-- Form section for editing tutorial -->
  <section class="page-section" id="form_tuto">
    <div class="container px-4 px-lg-5">
      <div class="row justify-content-center">
        <div class="col-lg-10">
          <h1 class="text-white">Edit Tutorial</h1>
          <!-- Form for editing tutorial -->
          <form method="post" enctype="multipart/form-data" id="edit-tutorial-form">
            {% csrf_token %}
            <!-- Display the tutorial form -->
            {{ tutorial_form.as_p }}
            <!-- Display the formset management form -->
            {{ formset.management_form }}

            <!-- Loop through each form in the formset and display it -->
            {% for form in formset %}
              {{ form.as_p }}
            {% endfor %}

            <!-- Buttons for saving changes, deleting tutorial, and publishing -->
            <div class="d-flex justify-content-center">
              <input type="submit" class="btn btn-secondary btn-xl m-1" value="Save Changes" />
              <a href="{% url 'delete_tutorial' id=tutorial.id %}" class="btn btn-secondary btn-xl m-1">Delete Tutorial</a>
              <input type="submit" class="btn btn-secondary btn-xl m-1" name="publish" value="Publish" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- JavaScript for handling delete confirmation -->
  <script>
    // Add event listener to delete button
    document.querySelector('.btn-delete').addEventListener('click', function (event) {
      // Prevent the default action of the link
      event.preventDefault();
      // Display confirmation dialog
      if (confirm('Are you sure you want to delete this tutorial?')) {
        // Redirect to delete URL
        window.location.href = event.target.href;
      }
    });
  </script>
{% endblock %}

WOCShAck#3/website/wocshack3/templates/blog_DIY/import_tutorial.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <header class="masthead">
    <section class="page-section" id="contact">
      <div class="container px-4 px-lg-5">
        <div class="row justify-content-center">
          <div class="col-lg-10">
            <h1 class="text-white">Import Tutorial</h1>

            <form method="post" enctype="multipart/form-data" action="{% url 'import_tutorial' %}">
              {% csrf_token %}

              <label class="text-white" for="file">Choose XML File:</label>
              <input type="file" name="file" required />
                <br/><br/>
              <button class="btn btn-primary btn-xl" type="submit">Import Tutorial</button>
            </form>
          </div>
        </div>
      </div>
    </section>
  </header>
{% endblock %}

WOCShAck#3/website/wocshack3/templates/blog_DIY/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <header class="masthead">
    <section class="page-section" id="contact">
      <div class="container px-4 px-lg-5">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <form id="contactForm" method="post">
              <div class="form-floating mb-3 d-flex justify-content-center">
                {{ register_form.username }}
                <label for="id_username">Username</label>
              </div>
              <div class="form-floating mb-3 d-flex justify-content-center">
                {{ register_form.email }}
                <label for="id_email">Email</label>
              </div>
              <div class="form-floating mb-3 d-flex justify-content-center">
                {{ register_form.password }}
                <label for="id_password">Password</label>
              </div>
              <div class="form-floating mb-3 d-flex justify-content-center">
                {{ register_form.confirm_password }}
                <label for="id_confirm_password">Confirm Password</label>
              </div>
              <div class="form-floating mb-3 d-flex justify-content-center">
                <p class="text-white">{{ register_form.authorize }} {{ register_form.authorize.label }}</p>
              </div>
              <p class="text-white text-center">By checking this box, you agree to log all your activities.</p>
              {% csrf_token %}
              <div class="text-center text-danger mb-3">{{ message }}</div>
              <div class="d-grid">
                <button class="btn btn-primary btn-xl" id="submitButton" type="submit">Register</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  </header>
{% endblock %}

WOCShAck#3/website/wocshack3/templates/blog_DIY/reset_password_hash.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <header class="masthead">
    <section class="page-section" id="contact">
      <div class="container px-4 px-lg-5">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h1 class="text-white">Change Password</h1>
            {% if password_form %}
            <form method="post">
              {% csrf_token %}
              <div class="form-floating mb-3 d-flex justify-content-center">
                {{ password_form.new_password }}
                <label for="id_new_password">New Password</label>
              </div>
              <div class="form-floating mb-3 d-flex justify-content-center">
                {{ password_form.confirm_new_password }}
                <label for="id_confirm_new_password">Confirm New Password</label>
              </div>
              <div class="text-center text-danger mb-3">{{ message }}</div>
              <div class="d-grid">
                <button class="btn btn-primary btn-xl" id="submitButton" type="submit">Change Password</button>
              </div>
            </form>
            {% else %}
            <div class="text-center text-white mb-3">{{ message }}</div>
            {% endif %}
          </div>
        </div>
      </div>
    </section>
  </header>
{% endblock %}